const hotId = "6e89ba73-a6eb-4198-a4c0-b231f89924fb";
const fesId = "ccda7800-50b9-4dc5-b572-6c45e09e330f";
const cakeId = "f6ce14d2-27ba-4051-bac4-02e14facee36";

export const cakeData = [
  {
    Name: "Thai Tea Boo Boo🧋",
    Size: "4 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 48,
    Code: "Th4",
  },
  {
    Name: "Thai Tea Boo Boo🧋",
    Size: "6 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 79,
    Code: "Th6",
  },
  {
    Name: "Osmanthus Oolong🍀",
    Size: "4 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 46,
    Code: "Os4",
  },
  {
    Name: "Osmanthus Oolong🍀",
    Size: "6 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 78,
    Code: "Os6",
  },
  {
    Name: "Osmanthus Oolong🍀",
    Size: "8 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 128,
    Code: "Os8",
  },
  {
    Name: "Coconut Latte☕️",
    Size: "4 inch",
    categoryId: hotId,
    Notes: "",
    Numbers: 46,
    Code: "Cl4",
  },
  {
    Name: "Coconut Latte☕️",
    Size: "6 inch",
    categoryId: hotId,
    Notes: "",
    Numbers: 78,
    Code: "Cl6",
  },
  {
    Name: "Coconut Latte☕️",
    Size: "8 inch",
    categoryId: hotId,
    Notes: "",
    Numbers: 128,
    Code: "Cl8",
  },
  {
    Name: "Spiced Tea Chestnuts🌰",
    Size: "4 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 56,
    Code: "Sp4",
  },
  {
    Name: "Spiced Tea Chestnuts🌰",
    Size: "6 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 88,
    Code: "Sp6",
  },
  {
    Name: "Coconut Pineapple🍍",
    Size: "4 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 46,
    Code: "Co4",
  },
  {
    Name: "Coconut Pineapple🍍",
    Size: "6 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 78,
    Code: "Co6",
  },
  {
    Name: "Coconut Pineapple🍍",
    Size: "8 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 128,
    Code: "Co8",
  },
  {
    Name: "Valentine's Day Limited",
    Size: "4 inch",
    categortId: fesId,
    Notes: "",
    Numbers: 79,
    Code: "Vl4",
  },
  {
    Name: "Valentine's Day Limited",
    Size: "6 inch",
    categortId: fesId,
    Notes: "",
    Numbers: 119,
    Code: "Vl6",
  },
  {
    Name: "Valentine's Day co-branding💄",
    Size: "4 inch",
    categortId: fesId,
    Notes: "",
    Numbers: 72,
    Code: "Va4",
  },
  {
    Name: "Valentine's Day co-branding💄",
    Size: "6 inch",
    categortId: fesId,
    Notes: "",
    Numbers: 188,
    Code: "Va6",
  },
  {
    Name: "Thai Tea Boo Boo🧋",
    Size: "8 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 130,
    Code: "Th8",
  },
  {
    Name: "Soy milk jicama🥛",
    Size: "4 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 49,
    Code: "So4",
  },
  {
    Name: "Soy milk jicama🥛",
    Size: "6 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 79,
    Code: "So6",
  },
  {
    Name: "Basque",
    Size: "6 inch",
    categoryId: cakeId,
    Notes: "",
    Numbers: 89,
    Code: "Ba6",
  },
  {
    Name: "Christmas Limited🎄",
    Size: "4 inch",
    categortId: fesId,
    Notes: "",
    Numbers: 108,
    Code: "Cs6",
  },
  {
    Name: "Christmas Limited🎄",
    Size: "6 inch",
    categortId: fesId,
    Notes: "",
    Numbers: 158,
    Code: "Cs4",
  },
];
