import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Signin from "./signin";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lullaby Lab</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signin />
    </>
  );
};

export default Home;
